name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hkusu/review-assign-action@v1.3.1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          max-num-of-reviewers: 5
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}' # success or failure

